apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: booking-platform
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: portport1234 # Change in production!
  POSTGRES_DB: booking_platform
